version: '3.8'
services:
  # The Application
  laravel-api:
    build:
      context: ./_docker
      dockerfile: api.docker
      target: development
    working_dir: /var/www
    container_name: laravel-api
    volumes:
      - ./${SPRINT}/API:/var/www:cached
    networks:
      - toolshop
    environment:
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=1"
      - "DB_PORT=3306"
      - "DB_HOST=toolshop-mariadb"
      - "host=localhost"
      - DISABLE_LOGGING=${DISABLE_LOGGING:-false}

  angular-ui:
    build:
      context: ./_docker
      dockerfile: ui.docker
      target: development
    working_dir: /app
    container_name:  angular-ui
    volumes:
      - ./${SPRINT}/UI:/app:cached
    ports:
      - 4200:4200
    command: >
      bash -c "npm install --force && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - toolshop


  # The Web Server
  web:
    build:
      context: ./_docker
      dockerfile: web.docker
    working_dir: /var/www
    volumes:
      - laravel-api:/var/www
    ports:
      - 8091:80
      - 8000:81
    depends_on:
      - laravel-api
    networks:
      - toolshop
    labels:
        - traefik.enable=true
        - traefik.http.routers.web.rule=Host(`toolshop.polteq-testing.com`)
        - traefik.http.routers.web.tls=true
        - traefik.http.routers.web.tls.certresolver=le



  composer:
    image: composer:2.6.6
    command: install --no-dev --optimize-autoloader --ignore-platform-req=ext-ffi && chown -R www-data /var/www && chmod 777 /var/www
    volumes_from:
      - laravel-api
    working_dir: /var/www

  # The Database
  toolshop-mariadb:
    image: yobasystems/alpine-mariadb:10.6.11
    ports:
      - 3306
    networks:
      - toolshop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: toolshop

volumes:
  laravel-api:

networks:
  toolshop:
    external: true
  frontend:
    external: true
